import CheckOut from "@/components/CheckOut";
export const metadata = {
  title: {
    // absolute: "",
    default: "Checkout",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <CheckOut />
    </>
  );
};

export default page;
