import Register from "@/components/Register";

export const metadata = {
  title: {
    // absolute: "",
    default: "Register",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Register />
    </>
  );
};

export default page;
