import About from "@/components/About";
export const metadata = {
  title: {
    // absolute: "",
    default: "About",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <About />
    </>
  );
};

export default page;
