import ContactUs from "@/components/ContactUs";
export const metadata = {
  title: {
    // absolute: "",
    default: "Contact Us",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <ContactUs />
    </>
  );
};

export default page;
