import Cart from "@/components/Cart";
export const metadata = {
  title: {
    // absolute: "",
    default: "Cart",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Cart />
    </>
  );
};

export default page;
