import Login from "@/components/Login";

export const metadata = {
  title: {
    // absolute: "",
    default: "Login",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Login />
    </>
  );
};

export default page;
