import Cart from "@/components/Cart";
import ProductList from "@/components/ProductList";
import ProductProvider from "@/components/ProductProvider";
export const metadata = {
  title: {
    // absolute: "",
    default: "Shop",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = async () => {
  const res = await fetch("https://fakestoreapi.com/products", {
    cache: "force-cache",
  });
  const products = await res.json();
  return (
    <>
      <ProductProvider products={products} />
      {/* <div>Products page</div> */}
      <ProductList />
    </>
  );
};

export default page;
