import Cart from "@/components/Cart";
import ProductList from "@/components/ProductList";
import ProductProvider from "@/components/ProductProvider";
export const metadata = {
  title: {
    // absolute: "",
    default: "Shop",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = async () => {

  const res = await fetch("https://dummyjson.com/products", {
    cache: "force-cache",
  });

  const data = await res.json();
  const products = data.products; // ✅ get the array of products

  return (
    <>
      <ProductProvider products={products} />
      {/* <div>Products page</div> */}
      <ProductList />
    </>
  );
};

export default page;
