import Payment from "@/components/Payment"
export const metadata = {
    title: {
      // absolute: "",
      default: "Payment",
      template: "%s",
    },
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <>
        <Payment />
    </>
)
}

export default page