import ResetPassword from "@/components/ResetPassword";

export const metadata = {
  title: {
    // absolute: "",
    default: "Reset Password",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <ResetPassword />
    </>
  );
};

export default page;
