import ProductDetails from "../../../components/ProductDetails";

export const metadata = {
  title: {
    default: "ProductDetails",
    template: "%s",
  },
  description: "Generated by create next app",
};

const page = async ({ params }) => {
  const res = await fetch(`https://dummyjson.com/products/${params.id}`, {
    cache: "force-cache",
    // next: { revalidate: 120 }, // ISR if needed
  });
  const product = await res.json();

  return (
    <>
      <ProductDetails product={product} />
    </>
  );
};

export default page;
